#!/bin/bash

# Check if frontend is running
# -x flag only match processes whose name (or command line if -f is
# specified) exactly match the pattern. 

if pgrep -f "./caen2018_dpp_frontend" > /dev/null
then
    echo "caen2018_dpp_frontend running"
else
    #caen2018_dpp_frontend has crashed
    echo "caen2018_dpp_frontend stopped"
    
    #stop current run
    odbedit -c stop
    echo "run stopped"
    sleep 15
    
    #start the caen2018_dpp_frontend
    echo "starting the caen2018_dpp_frontend"
    /home/daq/caen2018/caen2018_dpp_frontend -D
    sleep 60

    if pgrep -f "./caen2018_dpp_frontend" > /dev/null
    then
	echo "caen2018_dpp_frontend running"
	odbedit -c 'start now'
	echo "starting a run"
    fi
fi


if pgrep -x "mlogger" > /dev/null
then
    echo "mlogger running"
else
    echo "mlogger stopped"
fi